vuepress-docs
typerefinery-ai/typerefinery.ai pull request #5
Opened 2022-03-16 13:53 UTC by Rahul139-stack

Please the review the code and approved it

2022-03-17 09:41 UTC, sanjayaapna requested changes

2022-03-17 09:41 UTC, sanjayaapna commented on .env
> +APPLICATION_ID=3HSP2MEZNG
It would be more clear if we mention for which purpose these constants are.

2022-03-17 09:41 UTC, sanjayaapna commented on README.md
> +# vuepress1
no need to change it's name

2022-03-17 09:41 UTC, sanjayaapna commented on README.md
> +# vuepress1
no need to change it's name

2022-03-21 05:29 UTC, wildone requested changes
can you please add `dist` folder to ignore.

2022-03-21 08:20 UTC, sanjayaapna approved these changes

2022-03-21 08:20 UTC, skumar84pal commented on .env
> +APPLICATION_ID=3HSP2MEZNG
It would be more clear if we mention for which purpose these constants are.

2022-03-21 08:21 UTC, sanjayaapna approved these changes

2022-03-21 12:06 UTC, wildone approved these changes

2022-03-21 12:06 UTC, merged